### ISSUE TITLE
how to get rid of --initial and take versioning into account

### ISSUE THREAD

**Issue by Chilipp** [hermes-hmc/ci-templates#10]
moin @poikilotherm @sdruskat @led02 and @daniel-mohr !

thanks for your great work on this! Unfortunately I could not take part in the workshop at the deRSE24, as I had my own workshop at exactly the same time. I created a bunch of software-templates that I use to maintain python packages and other stuff (https://events.hifis.net/event/994/contributions/7994/) and I would very much like to integrate the hermes workflow as an option here. And so far, it works quite well

https://codebase.helmholtz.cloud/hcdc/software-templates/python-package-template/-/merge_requests/31

and I created a small demo repository based on this template at https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/ that publishes stuff to sandbox.zenodo.org

as I am very new to the hermes workflow, please forgive me, when there are shortcomings in my understanding how all of this works.

I was able to publish the demo-package to sandbox.zenodo.org from the hermes workflow (see https://sandbox.zenodo.org/records/34392) for instance (done [in this pipeline](https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/-/pipelines/359439)), but with the `--initial` option, I have now two different repositories in zenodo:

- record [34392](https://sandbox.zenodo.org/records/34392) from [commit `b05e03e0`](https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/-/commit/b05e03e0297d372087bd331b1e4946384cd487d1), and 
- and record [34347](https://sandbox.zenodo.org/records/34347) from [commit `c3e3ed48`](https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/-/commit/c3e3ed48)

I would have expected, that hermes uses the same repository on zenodo and just create a new version here. but apparently, it creates an entire new repository and does not use zenodos versioning approach. I presume that this is because of the `--initial` option in the `hermes deposit` command, but when I try to remove it, hermes complains that this is needed (see [this pipeline](https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/-/jobs/1541120))

as a second point (and if you like, I can open a new issue for this), is there a possibility such that we can specify the versioning when the repository is created? My package is using versioneer here and [zenodos rest API also supports using a custom version](https://developers.zenodo.org/#representation). currently, hermes just publishes the packages a `v1` on zenodo

**Comment by Chilipp** [comment]
awesome! I can work with this, thank you :smiley:

**Comment by daniel-mohr** [comment]
@Chilipp In your [hermes-ci-demo/](https://codebase.helmholtz.cloud/hcdc/software-templates/demos/hermes-ci-demo/)  you have many owners. How do you handle the zenodo token? (cf. https://github.com/hermes-hmc/hermes/issues/203)

If you provide the zenodo token as CI variable `HERMES_PUSH_TOKEN` you shared it at least with every owner and maintainer. As it is used in a temporary branch (created and deleted by hermes) I expect further the CI variable is not protected and could be used as developer in every branch with code defined by a developer.

Otherwise I would be very interested how you overcome this problem. Any hints?

**Comment by Chilipp** [comment]
moin @daniel-mohr! yes, this is indeed a problem. and one cannot protect this variable because the branches that hermes create are not protected ones (otherwise hermes would not be able to delete the branches for curation).

so my only solution (which would at least reduce the risk for other projects) is to create a deposit-specific account at https://zenodo.org and use the token from this page. If a developer in a repo then decides to make evil things, he or she can at least only to it for the specific project that he or she has access to.

do you have any other idea?

**Comment by led02** [comment]
Yes, Hermes could be used in the workflow of @daniel-mohr to do the conversion (replace cffconvert) and deposition (replace ja, curl).Von meinem iPhone gesendetAm 13.03.2024 um 10:09 schrieb daniel-mohr ***@***.***>:﻿
In my comment hermes-hmc/hermes#203 (comment) I tried to describe some possibilities -- but these are not implemented!
In hermes-hmc/hermes#203 (comment) I mentioned another workflow deploy_deploy2zenodo_to_zenodo. But this is not hermes! And it does not do the harvesting step -- maybe it could be joined with hermes somehow.
