### ISSUE TITLE
license mismatch

### ISSUE THREAD

**Issue by daniel-mohr** [hermes-hmc/ci-templates#8]
https://github.com/hermes-hmc/ci-templates/blob/b3a83b8f394438fdc2f049f724d55d4318d1e8c8/gitlab/hermes-ci.yml#L3

But in [README.md](https://github.com/hermes-hmc/ci-templates/tree/main#license) is `CC0-1.0` used.

**Comment by led02** [comment]
Oh, what a faux pas... CC0 ist what we want.
